POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "test title",
  "author": "noone",
  "url": "www.google.com",
  "likes": 1234,
  "userId": "5f9559796e04f4109ac800aa"
}